import { ProblemType, PaymentMethod } from './types';

export const problemTypesMap: Record<string, ProblemType[]> = {
    'Kebocoran': [
        { id: 'plafon_dak', label: "Plafon Bocor (Dak)" },
        { id: 'pipa_pecah', label: "Pipa Pecah / Bocor" },
        { id: 'rembes_pipa', label: "Rembes dari Pipa" },
        { id: 'genteng_bocor', label: "Perbaikan Genteng Bocor" },
        { id: 'dak_bocor', label: "Perbaikan Dak Bocor" },
        { id: 'plafon_genteng', label: "Plafon Bocor (Genteng)" },
        { id: 'plafon_tetes', label: "Perbaikan Plafon Setelah Bocor Teratasi" },
    ],
    'Cat': [
        { id: 'cat_dinding_dalam', label: "Cat Dinding Dalam (Interior)" },
        { id: 'cat_dinding_luar', label: "Cat Dinding Luar (Eksterior)" },
        { id: 'cat_plafon', label: "Cat Plafon" },
        { id: 'cat_pagar', label: "Cat Pagar Besi / Kayu" },
        { id: 'kelupas_cat', label: "Perbaikan Cat Mengelupas / Jamur" },
        { id: 'cat_pintu', label: "Cat Pintu & Jendela" },
    ],
    'Keramik': [
        { id: 'pasang_baru', label: "Pasang Keramik Baru" },
        { id: 'bongkar_pasang', label: "Bongkar & Pasang Keramik" },
        { id: 'keramik_pecah', label: "Perbaikan Keramik Pecah / Retak" },
        { id: 'pasang_granit', label: "Pasang Granit / Marmer" },
        { id: 'nat_keramik', label: "Perbaikan Nat Keramik" },
        { id: 'keramik_kamar_mandi', label: "Keramik Kamar Mandi" },
    ],
    'Listrik': [
        { id: 'korsleting', label: "Perbaikan Korsleting Listrik" },
        { id: 'tambah_titik', label: "Tambah Titik Lampu / Stopkontak" },
        { id: 'ganti_mcb', label: "Ganti MCB / Sekring" },
        { id: 'pasang_lampu', label: "Pasang / Ganti Lampu Gantung" },
        { id: 'instalasi_baru', label: "Instalasi Listrik Baru" },
        { id: 'panel_listrik', label: "Perbaikan Panel Listrik" },
    ],
    'Pipa': [
        { id: 'pipa_mampet', label: "Pipa Saluran Mampet" },
        { id: 'krran_rusak', label: "Ganti Kran Air Rusak" },
        { id: 'pasang_pompa', label: "Pasang / Servis Pompa Air" },
        { id: 'tambah_jalur', label: "Instalasi Jalur Pipa Baru" },
        { id: 'toren_air', label: "Instalasi / Kuras Toren Air" },
    ],
    'Sanitasi': [
        { id: 'wc_mampet', label: "WC / Toilet Mampet" },
        { id: 'pasang_kloset', label: "Pasang Kloset Duduk / Jongkok" },
        { id: 'wastafel', label: "Pasang / Perbaikan Wastafel" },
        { id: 'septictank', label: "Sedot / Perbaikan Septic Tank" },
        { id: 'shower', label: "Instalasi Shower & Water Heater" },
    ],
    'Konsultan': [
        { id: 'konsultasi_bangun', label: "Konsultasi Bangun Rumah Baru" },
        { id: 'konsultasi_renov', label: "Konsultasi Renovasi Total" },
        { id: 'hitung_rab', label: "Perhitungan RAB" },
        { id: 'cek_struktur', label: "Pengecekan Struktur Bangunan" },
    ],
    'Plafon': [
        { id: 'pasang_gypsum', label: "Pasang Plafon Gypsum" },
        { id: 'pasang_pvc', label: "Pasang Plafon PVC" },
        { id: 'plafon_jebol', label: "Perbaikan Plafon Jebol / Retak" },
        { id: 'lis_plafon', label: "Pemasangan Lis Plafon" },
        { id: 'rangka_plafon', label: "Perbaikan Rangka Plafon" },
    ],
    'Dinding': [
        { id: 'tembok_retak', label: "Perbaikan Tembok Retak Rambut" },
        { id: 'tembok_lembab', label: "Perbaikan Tembok Lembab / Rembes" },
        { id: 'plester_aci', label: "Jasa Plester & Aci Dinding" },
        { id: 'partisi', label: "Pembuatan Partisi Ruangan" },
        { id: 'pasang_bata', label: "Pasang Bata / Hebel" },
    ],
    'Pintu': [
        { id: 'pintu_seret', label: "Perbaikan Pintu Turun / Seret" },
        { id: 'ganti_engsel', label: "Ganti Engsel / Kunci Pintu" },
        { id: 'pasang_kusen', label: "Pasang Kusen Pintu / Jendela" },
        { id: 'pintu_aluminium', label: "Pembuatan Pintu Aluminium" },
        { id: 'kaca_jendela', label: "Ganti Kaca Jendela Pecah" },
    ],
    'Atap': [
        { id: 'baja_ringan', label: "Pasang Rangka Baja Ringan" },
        { id: 'ganti_genteng', label: "Ganti Genteng Pecah / Melorot" },
        { id: 'karpet_talang', label: "Perbaikan Karpet / Talang Air" },
        { id: 'cat_genteng', label: "Pengecatan Atap / Genteng" },
        { id: 'pasang_asbes', label: "Pasang Asbes / Spandek" },
    ],
    'Dapur': [
        { id: 'kitchen_set', label: "Pembuatan Kitchen Set" },
        { id: 'meja_dapur', label: "Buat Meja Dapur Cor / Granit" },
        { id: 'pasang_sink', label: "Pasang Kitchen Sink" },
        { id: 'renov_dapur', label: "Renovasi Total Dapur" },
        { id: 'penyedot_asap', label: "Instalasi Cooker Hood" },
    ],
    'Konstruksi': [
        { id: 'tambah_lantai', label: "Ngedak / Tambah Lantai" },
        { id: 'bangun_baru', label: "Bangun Rumah dari Nol" },
        { id: 'renovasi_total', label: "Renovasi Rumah Total" },
        { id: 'garasi', label: "Pembuatan Garasi / Carport" },
        { id: 'kolam_renang', label: "Pembuatan Kolam Renang" },
    ],
    'Pagar': [
        { id: 'las_pagar', label: "Las Pagar Besi Lepas" },
        { id: 'bikin_pagar', label: "Pembuatan Pagar Baru" },
        { id: 'cat_ulang_pagar', label: "Cat Ulang Pagar" },
        { id: 'pagar_tembok', label: "Pembuatan Pagar Tembok" },
        { id: 'ganti_roda', label: "Ganti Roda Pagar" },
    ],
    'Taman': [
        { id: 'potong_rumput', label: "Potong Rumput & Rapikan Taman" },
        { id: 'buat_taman', label: "Pembuatan Taman Baru" },
        { id: 'kolam_ikan', label: "Pembuatan Kolam Ikan" },
        { id: 'tanam_pohon', label: "Jasa Tanam Pohon / Tanaman Hias" },
        { id: 'system_siram', label: "Instalasi Sistem Penyiraman" },
    ],
    'Pondasi': [
        { id: 'cakar_ayam', label: "Pembuatan Cakar Ayam" },
        { id: 'suntik_beton', label: "Suntik Beton / Penguatan Struktur" },
        { id: 'pondasi_batu', label: "Pasang Pondasi Batu Kali" },
        { id: 'sloof', label: "Pengecoran Sloof & Kolom" },
    ],
    'Desain': [
        { id: 'desain_3d', label: "Desain Arsitektur 3D" },
        { id: 'gambar_kerja', label: "Gambar Kerja (DED)" },
        { id: 'desain_interior', label: "Desain Interior 3D" },
        { id: 'konsul_layout', label: "Konsultasi Layout Ruangan" },
    ],
    'Interior': [
        { id: 'wallpaper', label: "Pasang Wallpaper Dinding" },
        { id: 'gorden', label: "Pemasangan Gorden / Blinds" },
        { id: 'parket', label: "Pasang Lantai Kayu / Vinyl" },
        { id: 'backdrop_tv', label: "Pembuatan Backdrop TV" },
        { id: 'plint_lantai', label: "Pemasangan Plint Lantai" },
    ],
    'Toilet': [
        { id: 'renov_toilet', label: "Renovasi Kamar Mandi Total" },
        { id: 'waterproofing_toilet', label: "Waterproofing Lantai Toilet" },
        { id: 'pasang_bathtub', label: "Pasang Bathtub / Shower Box" },
        { id: 'ganti_keramik_wc', label: "Ganti Keramik Toilet" },
    ],
    'Jasa Angkat': [
        { id: 'pindahan', label: "Jasa Angkat Pindahan Rumah" },
        { id: 'buang_puing', label: "Jasa Buang Puing Bangunan" },
        { id: 'angkat_material', label: "Kuli Angkat Material" },
        { id: 'bersih_rumah', label: "Pembersihan Pasca Renovasi" },
    ],
    'Conblock': [
        { id: 'pasang_paving', label: "Pasang Paving Block Baru" },
        { id: 'servis_paving', label: "Perbaikan Paving Ambles" },
        { id: 'pasang_grassblock', label: "Pasang Grass Block" },
        { id: 'cor_jalan', label: "Pengecoran Jalan" },
    ],
    'Aluminium': [
        { id: 'jendela_alum', label: "Pembuatan Jendela Aluminium" },
        { id: 'pintu_alum', label: "Pembuatan Pintu Aluminium" },
        { id: 'partisi_kaca', label: "Partisi Kaca Aluminium" },
        { id: 'servis_alum', label: "Servis Kusen Aluminium" },
    ],
    'Exhaust Fan': [
        { id: 'pasang_exhaust', label: "Pasang Exhaust Fan Dinding/Plafon" },
        { id: 'servis_exhaust', label: "Servis / Bersihkan Exhaust Fan" },
        { id: 'bobok_lubang', label: "Bobok Lubang Exhaust Baru" },
    ],
    'Kipas Angin': [
        { id: 'pasang_kipas', label: "Pasang Kipas Angin Gantung" },
        { id: 'pasang_kipas_dinding', label: "Pasang Kipas Dinding" },
        { id: 'servis_kipas', label: "Perbaikan Instalasi Kipas" },
    ],
    'Batu Alam': [
        { id: 'pasang_batu_alam', label: "Pasang Dinding Batu Alam" },
        { id: 'coating_batu', label: "Coating / Vernis Batu Alam" },
        { id: 'lantai_batu', label: "Pasang Lantai Batu Alam" },
        { id: 'perbaikan_batu', label: "Perbaikan Batu Alam Lepas" },
    ],
    'Lemari': [
        { id: 'lemari_custom', label: "Pembuatan Lemari Custom (Wardrobe)" },
        { id: 'rak_buku', label: "Pembuatan Rak Buku / Display" },
        { id: 'servis_lemari', label: "Perbaikan Pintu / Engsel Lemari" },
        { id: 'bongkar_lemari', label: "Bongkar Pasang Lemari" },
    ],
    'Tangki Air': [
        { id: 'pasang_toren', label: "Instalasi Tangki Air Baru" },
        { id: 'kuras_toren', label: "Kuras / Bersihkan Tangki Air" },
        { id: 'radar_toren', label: "Pasang / Ganti Radar Otomatis" },
        { id: 'buat_menara', label: "Pembuatan Menara Toren Besi/Beton" },
    ],
    'Water Heater': [
        { id: 'pasang_wh_listrik', label: "Pasang Water Heater Listrik" },
        { id: 'pasang_wh_gas', label: "Pasang Water Heater Gas" },
        { id: 'servis_wh', label: "Servis / Perbaikan Water Heater" },
        { id: 'instalasi_pipa_wh', label: "Instalasi Pipa Panas Dingin" },
    ],
    'Kanopi': [
        { id: 'kanopi_baja', label: "Pasang Kanopi Baja Ringan" },
        { id: 'kanopi_besi', label: "Pasang Kanopi Besi Hollow" },
        { id: 'ganti_atap_kanopi', label: "Ganti Atap Kanopi (Alderon/Poly)" },
        { id: 'cat_kanopi', label: "Cat Ulang Rangka Kanopi" },
    ],
    'Lantai': [
        { id: 'poles_lantai', label: "Poles Lantai Marmer / Teraso" },
        { id: 'aci_lantai', label: "Aci Lantai Semen Ekspos" },
        { id: 'epoxy', label: "Cat Epoxy Lantai" },
        { id: 'perataan_lantai', label: "Perataan Lantai (Levelling)" },
    ],
    'Cuci Toren': [
        { id: 'cuci_toren_kecil', label: "Cuci Toren < 1000 Liter" },
        { id: 'cuci_toren_besar', label: "Cuci Toren > 1000 Liter" },
        { id: 'sterilisasi_air', label: "Sterilisasi Saluran Air" },
        { id: 'filter_air', label: "Pasang Filter Air Bersih" },
    ],
    'Kenek': [
        { id: 'bantu_harian', label: "Jasa Kenek Harian" },
        { id: 'aduk_semen', label: "Bantu Aduk Semen / Pasir" },
        { id: 'bersih_material', label: "Bantu Bersihkan Sisa Material" },
    ],
    // Default fallback
    'default': [
        { id: 'survey', label: "Survey Kerusakan" },
        { id: 'konsultasi', label: "Konsultasi Teknis" },
        { id: 'perbaikan_ringan', label: "Perbaikan Ringan" },
        { id: 'perbaikan_besar', label: "Perbaikan Besar / Renovasi" },
    ]
};

export const paymentMethods: PaymentMethod[] = [
    { id: 'gopay', name: 'GoPay', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/gopay_logo_icon_169325.png', balance: 2500000 },
    { id: 'ovo', name: 'OVO', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/ovo_logo_icon_169328.png', balance: 150000 },
    { id: 'dana', name: 'DANA', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/dana_logo_icon_169327.png', balance: 50000 },
    { id: 'bca', name: 'BCA Virtual Account', type: 'va', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/bca_logo_icon_169326.png', description: 'Cek otomatis' },
    { id: 'mandiri', name: 'Mandiri Virtual Account', type: 'va', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/mandiri_logo_icon_169329.png', description: 'Cek otomatis' },
];
