import { ProblemType, PaymentMethod } from './types';

export const problemTypesMap: Record<string, ProblemType[]> = {
    'Kebocoran': [
        { id: 'plafon_dak', label: "Plafon Bocor (Dak)", handymanType: 'Tukang Atap' },
        { id: 'pipa_pecah', label: "Pipa Pecah / Bocor", handymanType: 'Tukang Pipa' },
        { id: 'rembes_pipa', label: "Rembes dari Pipa", handymanType: 'Tukang Pipa' },
        { id: 'genteng_bocor', label: "Perbaikan Genteng Bocor", handymanType: 'Tukang Atap' },
        { id: 'dak_bocor', label: "Perbaikan Dak Bocor", handymanType: 'Tukang Atap' },
        { id: 'plafon_genteng', label: "Plafon Bocor (Genteng)", handymanType: 'Tukang Plafon' },
        { id: 'plafon_tetes', label: "Perbaikan Plafon Setelah Bocor Teratasi", handymanType: 'Tukang Plafon' },
    ],
    'Cat': [
        { id: 'cat_dinding_dalam', label: "Cat Dinding Dalam (Interior)", handymanType: 'Tukang Cat' },
        { id: 'cat_dinding_luar', label: "Cat Dinding Luar (Eksterior)", handymanType: 'Tukang Cat', needsKenek: true },
        { id: 'cat_plafon', label: "Cat Plafon", handymanType: 'Tukang Cat' },
        { id: 'cat_pagar', label: "Cat Pagar Besi / Kayu", handymanType: 'Tukang Cat' },
        { id: 'kelupas_cat', label: "Perbaikan Cat Mengelupas / Jamur", handymanType: 'Tukang Cat' },
        { id: 'cat_pintu', label: "Cat Pintu & Jendela", handymanType: 'Tukang Cat' },
    ],
    'Keramik': [
        { id: 'pasang_baru', label: "Pasang Keramik Baru", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'bongkar_pasang', label: "Bongkar & Pasang Keramik", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'keramik_pecah', label: "Perbaikan Keramik Pecah / Retak", handymanType: 'Tukang Bangunan' },
        { id: 'pasang_granit', label: "Pasang Granit / Marmer", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'nat_keramik', label: "Perbaikan Nat Keramik", handymanType: 'Tukang Bangunan' },
        { id: 'keramik_kamar_mandi', label: "Keramik Kamar Mandi", handymanType: 'Tukang Bangunan', needsKenek: true },
    ],
    'Listrik': [
        { id: 'korsleting', label: "Perbaikan Korsleting Listrik", handymanType: 'Tukang Listrik' },
        { id: 'tambah_titik', label: "Tambah Titik Lampu / Stopkontak", handymanType: 'Tukang Listrik' },
        { id: 'ganti_mcb', label: "Ganti MCB / Sekring", handymanType: 'Tukang Listrik' },
        { id: 'pasang_lampu', label: "Pasang / Ganti Lampu Gantung", handymanType: 'Tukang Listrik' },
        { id: 'instalasi_baru', label: "Instalasi Listrik Baru", handymanType: 'Tukang Listrik', needsKenek: true },
        { id: 'panel_listrik', label: "Perbaikan Panel Listrik", handymanType: 'Tukang Listrik' },
    ],
    'Pipa': [
        { id: 'pipa_mampet', label: "Pipa Saluran Mampet", handymanType: 'Tukang Pipa' },
        { id: 'krran_rusak', label: "Ganti Kran Air Rusak", handymanType: 'Tukang Pipa' },
        { id: 'pasang_pompa', label: "Pasang / Servis Pompa Air", handymanType: 'Tukang Pipa' },
        { id: 'tambah_jalur', label: "Instalasi Jalur Pipa Baru", handymanType: 'Tukang Pipa', needsKenek: true },
        { id: 'toren_air', label: "Instalasi / Kuras Toren Air", handymanType: 'Tukang Pipa' },
    ],
    'Sanitasi': [
        { id: 'wc_mampet', label: "WC / Toilet Mampet", handymanType: 'Tukang Pipa' },
        { id: 'pasang_kloset', label: "Pasang Kloset Duduk / Jongkok", handymanType: 'Tukang Pipa' },
        { id: 'wastafel', label: "Pasang / Perbaikan Wastafel", handymanType: 'Tukang Pipa' },
        { id: 'septictank', label: "Sedot / Perbaikan Septic Tank", handymanType: 'Tukang Pipa' },
        { id: 'shower', label: "Instalasi Shower & Water Heater", handymanType: 'Tukang Pipa' },
    ],
    'Konsultan': [
        { id: 'konsultasi_bangun', label: "Konsultasi Bangun Rumah Baru", handymanType: 'Ahli Bangunan' },
        { id: 'konsultasi_renov', label: "Konsultasi Renovasi Total", handymanType: 'Ahli Bangunan' },
        { id: 'hitung_rab', label: "Perhitungan RAB", handymanType: 'Ahli Bangunan' },
        { id: 'cek_struktur', label: "Pengecekan Struktur Bangunan", handymanType: 'Ahli Bangunan' },
    ],
    'Plafon': [
        { id: 'pasang_gypsum', label: "Pasang Plafon Gypsum", handymanType: 'Tukang Plafon' },
        { id: 'pasang_pvc', label: "Pasang Plafon PVC", handymanType: 'Tukang Plafon' },
        { id: 'plafon_jebol', label: "Perbaikan Plafon Jebol / Retak", handymanType: 'Tukang Plafon' },
        { id: 'lis_plafon', label: "Pemasangan Lis Plafon", handymanType: 'Tukang Plafon' },
        { id: 'rangka_plafon', label: "Perbaikan Rangka Plafon", handymanType: 'Tukang Plafon' },
    ],
    'Dinding': [
        { id: 'tembok_retak', label: "Perbaikan Tembok Retak Rambut", handymanType: 'Tukang Bangunan' },
        { id: 'tembok_lembab', label: "Perbaikan Tembok Lembab / Rembes", handymanType: 'Tukang Bangunan' },
        { id: 'plester_aci', label: "Jasa Plester & Aci Dinding", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'partisi', label: "Pembuatan Partisi Ruangan", handymanType: 'Tukang Bangunan' },
        { id: 'pasang_bata', label: "Pasang Bata / Hebel", handymanType: 'Tukang Bangunan', needsKenek: true },
    ],
    'Pintu': [
        { id: 'pintu_seret', label: "Perbaikan Pintu Turun / Seret", handymanType: 'Tukang Kayu' },
        { id: 'ganti_engsel', label: "Ganti Engsel / Kunci Pintu", handymanType: 'Tukang Kayu' },
        { id: 'pasang_kusen', label: "Pasang Kusen Pintu / Jendela", handymanType: 'Tukang Kayu' },
        { id: 'pintu_aluminium', label: "Pembuatan Pintu Aluminium", handymanType: 'Tukang Aluminium' },
        { id: 'kaca_jendela', label: "Ganti Kaca Jendela Pecah", handymanType: 'Tukang Kaca' },
    ],
    'Atap': [
        { id: 'baja_ringan', label: "Pasang Rangka Baja Ringan", handymanType: 'Tukang Atap', needsKenek: true },
        { id: 'ganti_genteng', label: "Ganti Genteng Pecah / Melorot", handymanType: 'Tukang Atap' },
        { id: 'karpet_talang', label: "Perbaikan Karpet / Talang Air", handymanType: 'Tukang Atap' },
        { id: 'cat_genteng', label: "Pengecatan Atap / Genteng", handymanType: 'Tukang Cat' },
        { id: 'pasang_asbes', label: "Pasang Asbes / Spandek", handymanType: 'Tukang Atap' },
    ],
    'Dapur': [
        { id: 'kitchen_set', label: "Pembuatan Kitchen Set", handymanType: 'Tukang Interior' },
        { id: 'meja_dapur', label: "Buat Meja Dapur Cor / Granit", handymanType: 'Tukang Bangunan' },
        { id: 'pasang_sink', label: "Pasang Kitchen Sink", handymanType: 'Tukang Pipa' },
        { id: 'renov_dapur', label: "Renovasi Total Dapur", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'penyedot_asap', label: "Instalasi Cooker Hood", handymanType: 'Tukang Listrik' },
    ],
    'Konstruksi': [
        { id: 'tambah_lantai', label: "Ngedak / Tambah Lantai", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'bangun_baru', label: "Bangun Rumah dari Nol", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'renovasi_total', label: "Renovasi Rumah Total", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'garasi', label: "Pembuatan Garasi / Carport", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'kolam_renang', label: "Pembuatan Kolam Renang", handymanType: 'Tukang Bangunan', needsKenek: true },
    ],
    'Pagar': [
        { id: 'las_pagar', label: "Las Pagar Besi Lepas", handymanType: 'Tukang Las' },
        { id: 'bikin_pagar', label: "Pembuatan Pagar Baru", handymanType: 'Tukang Las', needsKenek: true },
        { id: 'cat_ulang_pagar', label: "Cat Ulang Pagar", handymanType: 'Tukang Cat' },
        { id: 'pagar_tembok', label: "Pembuatan Pagar Tembok", handymanType: 'Tukang Bangunan' },
        { id: 'ganti_roda', label: "Ganti Roda Pagar", handymanType: 'Tukang Las' },
    ],
    'Taman': [
        { id: 'potong_rumput', label: "Potong Rumput & Rapikan Taman", handymanType: 'Tukang Taman' },
        { id: 'buat_taman', label: "Pembuatan Taman Baru", handymanType: 'Tukang Taman', needsKenek: true },
        { id: 'kolam_ikan', label: "Pembuatan Kolam Ikan", handymanType: 'Tukang Taman' },
        { id: 'tanam_pohon', label: "Jasa Tanam Pohon / Tanaman Hias", handymanType: 'Tukang Taman' },
        { id: 'system_siram', label: "Instalasi Sistem Penyiraman", handymanType: 'Tukang Pipa' },
    ],
    'Pondasi': [
        { id: 'cakar_ayam', label: "Pembuatan Cakar Ayam", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'suntik_beton', label: "Suntik Beton / Penguatan Struktur", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'pondasi_batu', label: "Pasang Pondasi Batu Kali", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'sloof', label: "Pengecoran Sloof & Kolom", handymanType: 'Tukang Bangunan', needsKenek: true },
    ],
    'Desain': [
        { id: 'desain_3d', label: "Desain Arsitektur 3D", handymanType: 'Arsitek' },
        { id: 'gambar_kerja', label: "Gambar Kerja (DED)", handymanType: 'Arsitek' },
        { id: 'desain_interior', label: "Desain Interior 3D", handymanType: 'Desainer Interior' },
        { id: 'konsul_layout', label: "Konsultasi Layout Ruangan", handymanType: 'Arsitek' },
    ],
    'Interior': [
        { id: 'wallpaper', label: "Pasang Wallpaper Dinding", handymanType: 'Tukang Interior' },
        { id: 'gorden', label: "Pemasangan Gorden / Blinds", handymanType: 'Tukang Interior' },
        { id: 'parket', label: "Pasang Lantai Kayu / Vinyl", handymanType: 'Tukang Interior' },
        { id: 'backdrop_tv', label: "Pembuatan Backdrop TV", handymanType: 'Tukang Interior' },
        { id: 'plint_lantai', label: "Pemasangan Plint Lantai", handymanType: 'Tukang Interior' },
    ],
    'Toilet': [
        { id: 'renov_toilet', label: "Renovasi Kamar Mandi Total", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'waterproofing_toilet', label: "Waterproofing Lantai Toilet", handymanType: 'Tukang Bangunan' },
        { id: 'pasang_bathtub', label: "Pasang Bathtub / Shower Box", handymanType: 'Tukang Pipa' },
        { id: 'ganti_keramik_wc', label: "Ganti Keramik Toilet", handymanType: 'Tukang Bangunan' },
    ],
    'Jasa Angkat': [
        { id: 'pindahan', label: "Jasa Angkat Pindahan Rumah", handymanType: 'Kenek' },
        { id: 'buang_puing', label: "Jasa Buang Puing Bangunan", handymanType: 'Kenek' },
        { id: 'angkat_material', label: "Kuli Angkat Material", handymanType: 'Kenek' },
        { id: 'bersih_rumah', label: "Pembersihan Pasca Renovasi", handymanType: 'Kenek' },
    ],
    'Conblock': [
        { id: 'pasang_paving', label: "Pasang Paving Block Baru", handymanType: 'Tukang Bangunan', needsKenek: true },
        { id: 'servis_paving', label: "Perbaikan Paving Ambles", handymanType: 'Tukang Bangunan' },
        { id: 'pasang_grassblock', label: "Pasang Grass Block", handymanType: 'Tukang Bangunan' },
        { id: 'cor_jalan', label: "Pengecoran Jalan", handymanType: 'Tukang Bangunan', needsKenek: true },
    ],
    'Aluminium': [
        { id: 'jendela_alum', label: "Pembuatan Jendela Aluminium", handymanType: 'Tukang Aluminium' },
        { id: 'pintu_alum', label: "Pembuatan Pintu Aluminium", handymanType: 'Tukang Aluminium' },
        { id: 'partisi_kaca', label: "Partisi Kaca Aluminium", handymanType: 'Tukang Aluminium' },
        { id: 'servis_alum', label: "Servis Kusen Aluminium", handymanType: 'Tukang Aluminium' },
    ],
    'Exhaust Fan': [
        { id: 'pasang_exhaust', label: "Pasang Exhaust Fan Dinding/Plafon", handymanType: 'Tukang Listrik' },
        { id: 'servis_exhaust', label: "Servis / Bersihkan Exhaust Fan", handymanType: 'Tukang Listrik' },
        { id: 'bobok_lubang', label: "Bobok Lubang Exhaust Baru", handymanType: 'Tukang Bangunan' },
    ],
    'Kipas Angin': [
        { id: 'pasang_kipas', label: "Pasang Kipas Angin Gantung", handymanType: 'Tukang Listrik' },
        { id: 'pasang_kipas_dinding', label: "Pasang Kipas Dinding", handymanType: 'Tukang Listrik' },
        { id: 'servis_kipas', label: "Perbaikan Instalasi Kipas", handymanType: 'Tukang Listrik' },
    ],
    'Batu Alam': [
        { id: 'pasang_batu_alam', label: "Pasang Dinding Batu Alam", handymanType: 'Tukang Bangunan' },
        { id: 'coating_batu', label: "Coating / Vernis Batu Alam", handymanType: 'Tukang Cat' },
        { id: 'lantai_batu', label: "Pasang Lantai Batu Alam", handymanType: 'Tukang Bangunan' },
        { id: 'perbaikan_batu', label: "Perbaikan Batu Alam Lepas", handymanType: 'Tukang Bangunan' },
    ],
    'Lemari': [
        { id: 'lemari_custom', label: "Pembuatan Lemari Custom (Wardrobe)", handymanType: 'Tukang Interior' },
        { id: 'rak_buku', label: "Pembuatan Rak Buku / Display", handymanType: 'Tukang Interior' },
        { id: 'servis_lemari', label: "Perbaikan Pintu / Engsel Lemari", handymanType: 'Tukang Interior' },
        { id: 'bongkar_lemari', label: "Bongkar Pasang Lemari", handymanType: 'Tukang Interior' },
    ],
    'Tangki Air': [
        { id: 'pasang_toren', label: "Instalasi Tangki Air Baru", handymanType: 'Tukang Pipa' },
        { id: 'kuras_toren', label: "Kuras / Bersihkan Tangki Air", handymanType: 'Tukang Pipa' },
        { id: 'radar_toren', label: "Pasang / Ganti Radar Otomatis", handymanType: 'Tukang Listrik' },
        { id: 'buat_menara', label: "Pembuatan Menara Toren Besi/Beton", handymanType: 'Tukang Las' },
    ],
    'Water Heater': [
        { id: 'pasang_wh_listrik', label: "Pasang Water Heater Listrik", handymanType: 'Tukang Listrik' },
        { id: 'pasang_wh_gas', label: "Pasang Water Heater Gas", handymanType: 'Tukang Pipa' },
        { id: 'servis_wh', label: "Servis / Perbaikan Water Heater", handymanType: 'Tukang Pipa' },
        { id: 'instalasi_pipa_wh', label: "Instalasi Pipa Panas Dingin", handymanType: 'Tukang Pipa' },
    ],
    'Kanopi': [
        { id: 'kanopi_baja', label: "Pasang Kanopi Baja Ringan", handymanType: 'Tukang Atap', needsKenek: true },
        { id: 'kanopi_besi', label: "Pasang Kanopi Besi Hollow", handymanType: 'Tukang Las', needsKenek: true },
        { id: 'ganti_atap_kanopi', label: "Ganti Atap Kanopi (Alderon/Poly)", handymanType: 'Tukang Atap' },
        { id: 'cat_kanopi', label: "Cat Ulang Rangka Kanopi", handymanType: 'Tukang Cat' },
    ],
    'Lantai': [
        { id: 'poles_lantai', label: "Poles Lantai Marmer / Teraso", handymanType: 'Tukang Bangunan' },
        { id: 'aci_lantai', label: "Aci Lantai Semen Ekspos", handymanType: 'Tukang Bangunan' },
        { id: 'epoxy', label: "Cat Epoxy Lantai", handymanType: 'Tukang Cat' },
        { id: 'perataan_lantai', label: "Perataan Lantai (Levelling)", handymanType: 'Tukang Bangunan' },
    ],
    'Cuci Toren': [
        { id: 'cuci_toren_kecil', label: "Cuci Toren < 1000 Liter", handymanType: 'Tukang Pipa' },
        { id: 'cuci_toren_besar', label: "Cuci Toren > 1000 Liter", handymanType: 'Tukang Pipa' },
        { id: 'sterilisasi_air', label: "Sterilisasi Saluran Air", handymanType: 'Tukang Pipa' },
        { id: 'filter_air', label: "Pasang Filter Air Bersih", handymanType: 'Tukang Pipa' },
    ],
    'Kenek': [
        { id: 'bantu_harian', label: "Jasa Kenek Harian", handymanType: 'Kenek' },
        { id: 'aduk_semen', label: "Bantu Aduk Semen / Pasir", handymanType: 'Kenek' },
        { id: 'bersih_material', label: "Bantu Bersihkan Sisa Material", handymanType: 'Kenek' },
    ],
    // Default fallback
    'default': [
        { id: 'survey', label: "Survey Kerusakan", handymanType: 'Mandor' }, // Defaulting to Mandor/Surveyor
        { id: 'konsultasi', label: "Konsultasi Teknis", handymanType: 'Konsultan' },
        { id: 'perbaikan_ringan', label: "Perbaikan Ringan", handymanType: 'Tukang Bangunan' },
        { id: 'perbaikan_besar', label: "Perbaikan Besar / Renovasi", handymanType: 'Tukang Bangunan' },
    ]
};

export const paymentMethods: PaymentMethod[] = [
    { id: 'gopay', name: 'GoPay', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/gopay_logo_icon_169325.png', balance: 2500000 },
    { id: 'ovo', name: 'OVO', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/ovo_logo_icon_169328.png', balance: 150000 },
    { id: 'dana', name: 'DANA', type: 'ewallet', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/dana_logo_icon_169327.png', balance: 50000 },
    { id: 'bca', name: 'BCA Virtual Account', type: 'va', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/bca_logo_icon_169326.png', description: 'Cek otomatis' },
    { id: 'mandiri', name: 'Mandiri Virtual Account', type: 'va', icon: 'https://cdn.icon-icons.com/icons2/2699/PNG/512/mandiri_logo_icon_169329.png', description: 'Cek otomatis' },
];
