-- Create junction table for Order <-> Handyman (Many-to-Many)
CREATE TABLE order_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pesanan_id BIGINT REFERENCES orders(pesanan_id) ON DELETE CASCADE,
  anggota_id BIGINT REFERENCES data_anggota(anggota_id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(pesanan_id, anggota_id)
);

-- Migrate existing data from the single 'tukang_id' column
INSERT INTO order_assignments (pesanan_id, anggota_id)
SELECT pesanan_id, tukang_id 
FROM orders 
WHERE tukang_id IS NOT NULL;

-- We don't drop the 'tukang_id' column immediately to prevent breaking running code, 
-- but we will stop using it in the application logic.
